name: SAGE BOT

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Packages
        run: npm install

      - name: Run SAGE BOT
        env:
          PHONENUMBER: ${{ secrets.PHONENUMBER }}

        run: node index.js
